### ISSUE TITLE
Live on Cli Talk at Vienna.rb Th Sept/1st @sektor5 ?

### ISSUE THREAD

**Issue by geraldb** [ryyppy/life-on-cli#1]
Hello @ryyppy This is Gerald (von Vienna.html) we met at Stahlstadt.js #10. Talked to the Vienna.rb orgs yesterday (at Ruby Habits). If you're interested they love to host your Life on the Command Line Talk (or better live performance). It's all set if the date works for you (Thu Sept/1st @ sektor5), see http://meetup.com/vienna-rb/events/233086079  Sorry not sure how to reach you by email. Sorry for the duplicate posting. PS: Just in case my email is gerald.bauer AT gmail.com

**Comment by ryyppy** [comment]
Wrote in the meetup group 👍

**Comment by geraldb** [comment]
Great thanks. Looking forward to your "Life on the Command Line" talk. Cheers.
